baseURL = 'https://tidalhq.com/'
languageCode = 'en-us'
title = 'TidalWave Tech'
theme = 'spectral'
defaultContentLanguage = "en"
paginate = "7"

[params]
fancyTitle = "TidalWave" # title for frontpage, may include image
copyright = "TidalWave Tech Inc"
description = 'Building the next wave of innovation in FinTech'
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
images = ["img/main-background.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

#[[params.menu.main]]
#url = '/news/'
#title = "News"

[params.one]
enable = false
title = 'Gental but Firm'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = false

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Tech innovation, gentle yet firm'
body = '''
'''

[[params.three.feature]]
icon = "fa-laptop"
title = "Following industrial standard"
body = "TidalWave platform speaks the language of the industry and interoperable with most."

[[params.three.feature]]
icon = "fa-code"
title = "Driven by tech"
body = "Breaking through technology from veterans in the space"

[[params.three.feature]]
icon = "fa-headphones"
title = "Easy to use by design"
body = "Our system do the hard work so you don't have to"

[[params.three.feature]]
icon = "fa-heart-o"
title = "Built for everyone"
body = "Democratizing financial tasks to every individual"

[params.cta]
enable = true 
title = "Stay tuned for more"
body = ""

[[params.cta.link]]
href = "mailto:contact@tidalhq.com"
text = "Contact Us"
special = true

#[[params.cta.link]]
#href = "#"
#text = "Learn More"
#special = false

[params.contact]
enable = false
title = "Contact"
email = "contact@tidalhq.com"
plain = true

# language specific options

[languages.en]
weight = 0
languageName = "English"
